
name: CI / CD
on: [push] # TO CHANGE: Should be on pull request
jobs:
  build:
    runs-on: macos-15
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Turn on 'editable' mode
        run: |
          pipenv install -e .
      - name: Print Runner OS
        run: |
          echo "Runner OS: ${{ runner.os }}"
          sw_vers
          pwd
      - name: Test with pytest
        run: |
          echo "KIVY_HOME=/Users/runner/work/tests_mymodule/tests_mymodule" >> "$GITHUB_ENV"
          echo $KIVY_HOME
          pipenv install "kivy[base]"
          echo "ls -al /Users/runner/"
          ls -al /Users/runner/
          echo "ls -al /Users/runner/work"
          ls -al /Users/runner/work
          echo "ls -al /Users/runner/work/tests_mymodule/"
          ls -al /Users/runner/work/tests_mymodule
          echo "ls -al /Users/runner/work/tests_mymodule/tests_mymodule"
          ls -al /Users/runner/work/tests_mymodule/tests_mymodule
          echo "ls -l /Users/runner/.local/share/virtualenvs/tests_mymodule-qobL2vCM/lib/python3.13/site-packages/kivy/core/window/"
          ls -l /Users/runner/.local/share/virtualenvs/tests_mymodule-qobL2vCM/lib/python3.13/site-packages/kivy/core/window/
          echo "ls -l /System/Library/Frameworks"
          ls -l /System/Library/Frameworks
          pipenv install pytest
          pipenv install pytest-mock
          pipenv --venv
          pipenv run python -m pytest
          echo $GITHUB_WORKSPACE
