
name: CI / CD
on: [push] # TO CHANGE: Should be on pull request
jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Turn on 'editable' mode
        run: |
          pipenv install -e .
      - name: Print Runner OS
        run: |
          echo "Runner OS: ${{ runner.os }}"
      - name: Install dependencies
        env:
          USE_ANGEL_GL_BACKEND: "0"
        run: |
          python -m pip install --upgrade pip
          python -m pip install "kivy[base]" 
          python -m pip install pytest
      - name: Test with pytest
        run: |
          python -m pytest