name: Build and test the package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: "3.11"
      - name: Build package
        run: |
          pipenv install build
          pipenv run python -m build .

  run_pytest:
    needs: [build]
    runs-on: macos-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Regenerate lock file
        run: |
          pipenv lock
      - name: Install dependencies
        env:
          USE_ANGLE_GL_BACKEND: "0"
        run: |
          pipenv install pytest 
          pipenv install pygame
          pipenv install "kivy[base]"
      - name: Turn on 'editable' mode
        run: |
          pipenv install -e .
      - name: Test with pytest
        env:
          USE_ANGLE_GL_BACKEND: "0"
        run: |
          pipenv run python -m pytest