
name: CI / CD
on: [push] # TO CHANGE: Should be on pull request
jobs:
  build:
    runs-on: macos-15
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Turn on 'editable' mode
        run: |
          pipenv install -e .
      - name: Print Runner OS
        run: |
          echo "Runner OS: ${{ runner.os }}"
          sw_vers

      - name: Test with pytest
        run: |
          pipenv install "kivy[base]"
          echo "ls -l /Users/runner/.local/share/virtualenvs/tests_mymodule-qobL2vCM/lib/python3.13/site-packages/kivy/core/window/"
          ls -l /Users/runner/.local/share/virtualenvs/tests_mymodule-qobL2vCM/lib/python3.13/site-packages/kivy/core/window/
          echo "ls -l /System/Library/Frameworks"
          ls -l /System/Library/Frameworks
          pipenv install pytest
          pipenv install pytest-mock
          pipenv --venv
          pipenv run python -m pytest
