name: CI / CD
on: [push] # TO CHANGE: Should be on pull request
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Turn on 'editable' mode
        run: |
          pipenv install -e .
      - name: Print Runner OS
        run: |
          echo "Runner OS: ${{ runner.os }}"
      - name: Print Sys info
        run: |
          lsb_release -a
          hostnamectl
          uname -r
          ls -l /usr/lib
      - name: Test with pytest
        run: |
          pipenv install kivy
          echo "ls -l /home/runner/work/tests_mymodule/tests_mymodule/"
          ls -l /home/runner/work/tests_mymodule/tests_mymodule/
          echo "ls -l /home/runner/.local/share/virtualenvs/tests_mymodule-4ykKIPa5/lib/python3.10/site-packages/kivy/input/providers"
          ls -l /home/runner/.local/share/virtualenvs/tests_mymodule-4ykKIPa5/lib/python3.10/site-packages/kivy/input/providers
          echo "copying mtdev.py"
          sudo cp /home/runner/work/tests_mymodule/tests_mymodule/mtdev.py /home/runner/.local/share/virtualenvs/tests_mymodule-4ykKIPa5/lib/python3.10/site-packages/kivy/input/providers
          echo "**after copy ls -l /home/runner/.local/share/virtualenvs/tests_mymodule-4ykKIPa5/lib/python3.10/site-packages/kivy/input/providers"
          ls -l /home/runner/.local/share/virtualenvs/tests_mymodule-4ykKIPa5/lib/python3.10/site-packages/kivy/input/providers
          pipenv install pytest
          pipenv install pytest-mock
          pipenv --venv
          echo "**after pipenv --venv"
          echo "ls -l /home/runner/work/tests_mymodule/tests_mymodule/"
          ls -l /home/runner/work/tests_mymodule/tests_mymodule/
          echo "ls -l /home/runner/.local/share/virtualenvs/tests_mymodule-4ykKIPa5/lib/python3.10/site-packages/kivy/input/providers"
          ls -l /home/runner/.local/share/virtualenvs/tests_mymodule-4ykKIPa5/lib/python3.10/site-packages/kivy/input/providers
          pipenv run python -m pytest
